### ISSUE TITLE
Build the data model

### ISSUE THREAD

**Issue by JarodXP** [JarodXP/blog-micro-framework#14]

**Comment by JarodXP** [comment]
@Tutt-J  : please find enclose for review the class diagramm and the data model.
[entities-classes.pdf](https://github.com/JarodXP/blog-micro-framework/files/4077795/entities-classes.pdf)
![dataModel](https://user-images.githubusercontent.com/20837809/72629941-94372e80-3951-11ea-9d4c-3a0081a9844f.png)

**Comment by JarodXP** [comment]
Corrections:
[entities-classes.pdf](https://github.com/JarodXP/blog-micro-framework/files/4081057/entities-classes.pdf)
XML to be loaded in SQL Designer - [https://ondras.zarovi.cz/sql/demo/](url)
![dataModel](https://user-images.githubusercontent.com/20837809/72667235-e80d4a80-3a19-11ea-9350-ee296eca6a0d.png)

**Comment by JarodXP** [comment]
@Tutt-J  : Last corrections:
**Class Diagramm:**
[entities-classes.pdf](https://github.com/JarodXP/blog-micro-framework/files/4081057/entities-classes.pdf)

**XML to be loaded in SQL Designer** - [https://ondras.zarovi.cz/sql/demo/](url):
[dataModel.txt](https://github.com/JarodXP/blog-micro-framework/files/4085021/dataModel.txt)

**Data model:**
![dataModel](https://user-images.githubusercontent.com/20837809/72708274-a936dc00-3b62-11ea-8dc4-06f2526692a6.png)

**Comment by Tutt-J** [comment]
Okay
